version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong!Passw0rd
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_strong!Passw0rd", "-Q", "SELECT 1"]
    volumes:
      - mssqldata:/var/opt/mssql

  api:
    build:
      context: ./BooksReviews.Api
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=BooksReviewsDb;User Id=sa;Password=Your_strong!Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=True
      - JwtSettings__Secret=SuperSecretKeyParaBooksReviews12345!
      - JwtSettings__Issuer=BooksReviewsApi
      - JwtSettings__Audience=BooksReviewsApp
    ports:
      - "5000:80"

  frontend:
    build:
      context: ./FrontBooksReviews
      dockerfile: Dockerfile
    ports:
      - "4200:80"

volumes:
  mssqldata:
